--- 
title: "Examining Social Media Disinformation"
author: "Kate Lassiter & Renato Russo "
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

This topic stands out to us as students who have grown up in the age of fake news and social media. When we receive information, we don't always go out of our way to fact check every headline. Our own internal bias may often lead us to accept false information as true, simply by cherry picking facts we already believe to be true. This is known as confirmation bias. This analysis sets off to study the effects of this bias, the susceptibility of individuals to fake, sensationalized articles, and the differences in open minded thinking across different political affiliations.

For example, one common assumption is that very conservative Republicans are not open minded and are unwilling to change their ways of thinking on important topics, such as religion. Another assumption could be that very liberal individuals like to play the devil's advocate and take the contrarian point of view. So, they read articles that are very conservative for a longer than average time in order to piece together a narrative of why the opposite might be true. We are hoping to test some of these sweeping generalizations about certain political factions. The aim of this analysis is to give a greater context as to whether behavior in this domain truly varies based on political agenda or whether it's other factors that make us more or less susceptible to fake news and changing our opinions.

If political extremism really plays a large role in our susceptibility to fake news, this shows that those who are most strongly republican or democratic are the ones being prayed upon by the ever increasing media circus in the United States. Many of the news stories played on cable television contain truth and lies, and the people who are most likely to watch the news are those who have the strongest political opinions. We are constantly bombarded by fake news, and this may lead to an increasing divide between political parties, especially among those with more extreme views on either end of the spectrum. When the country is divided over these fundamental issues, and people are constantly shown false news that push them further to the extreme, this poses a major challenge to society. In order to address and combat confirmation bias and fake news, we must first identify what makes us most susceptible and attempt to modify our behaviors. 