# Interactive component

<iframe src="circs.html" width="900" height="600"></iframe>
No analysis can be complete without a review of deviations from the norm. In this case, mean reading times for politically discordant headlines (pro-conservative for Democrats, pro-liberal for Republicans) are normalized across participants to identify individuals that read politically contrasting articles for a longer than average time. In the interactive above, the dashed gray line represents the mean and each red dashed line represents one standard deviation above the mean. No observations fall below one standard deviation of the mean. Each circle is colored according to the participant's political ideology. Unsurprisingly, it tends to be participants on the extremes of the ideology spectrum, either extremely liberal (score 1-2) or extremely conservative (6-7), that spend the longest time reading headlines that disagree with their political agenda. This is often the very foundation of news, to sensationalize people with headlines that shock them or go against there point of view. This leads them to read articles for longer, discuss them with friends, and often believe the article on face value without doing any further research. 



We present here a chart of all participants with reading times greater than or equal to one standard deviation above the mean. These are the points that are at least past the first dashed red line in the interactive above. These participants spent longer than "normal" reading these headlines. Of the 30 participants that met this criteria, 23 were either extremely liberal or extremely conservative. Further, of the 14 participants that had reading times two deviations above the average, 11 were either extremely liberal or extremely conservative. This reinforces the belief that those who are strongly opinionated are more drawn to articles that conflict with their beliefs than someone who is more moderately inclined.
```{r}
library(dplyr)
library(ggplot2)
#Getting zscores
dataset=select(dataset,c("discordant_rt","ideology"))
dataset$zscore=scale(dataset$discordant_rt)

#Filtering the data set to those who have discordant scores at least one deviation from the mean, getting a count by ideology
one=filter(dataset,zscore>=1)
one=one %>%
  group_by(ideology)%>%
  count()
one=as.data.frame(one)
one=one[order(one$ideology),]

ggplot(data=one, aes(x=ideology, y=n,fill=ideology)) + geom_bar(stat="identity") + 
      xlab("Ideology (extremely liberal to extremely conservative)") + ylab("Number of Participants")+
  scale_fill_manual(values = c("#277DA1",
                               "#8C9ACC",
                               "#95D1FF",
                               "#EECDF1",
                               "#F58CAD",
                               "#FA6164",
                               "#F94144"))+
  scale_y_continuous(n.breaks=10)+
  theme_minimal() +
  ggtitle("Longest Reading Times")
```
