<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Data | Disinformation, social media, and political orientation</title>
  <meta name="description" content="Chapter 3 Data | Disinformation, social media, and political orientation" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Data | Disinformation, social media, and political orientation" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Data | Disinformation, social media, and political orientation" />
  
  
  

<meta name="author" content="Kate Lassiter, Renato Russo" />


<meta name="date" content="2022-12-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="proposal.html"/>
<link rel="next" href="results.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">media_disinformation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="proposal.html"><a href="proposal.html"><i class="fa fa-check"></i><b>2</b> Proposal</a>
<ul>
<li class="chapter" data-level="2.1" data-path="proposal.html"><a href="proposal.html#research-topic"><i class="fa fa-check"></i><b>2.1</b> Research topic</a></li>
<li class="chapter" data-level="2.2" data-path="proposal.html"><a href="proposal.html#data-availability"><i class="fa fa-check"></i><b>2.2</b> Data availability</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>3</b> Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data.html"><a href="data.html#sources"><i class="fa fa-check"></i><b>3.1</b> Sources</a></li>
<li class="chapter" data-level="3.2" data-path="data.html"><a href="data.html#cleaning-transformation"><i class="fa fa-check"></i><b>3.2</b> Cleaning / transformation</a></li>
<li class="chapter" data-level="3.3" data-path="data.html"><a href="data.html#missing-value-analysis"><i class="fa fa-check"></i><b>3.3</b> Missing value analysis</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>4</b> Results</a></li>
<li class="chapter" data-level="5" data-path="interactive-component.html"><a href="interactive-component.html"><i class="fa fa-check"></i><b>5</b> Interactive component</a></li>
<li class="chapter" data-level="6" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>6</b> Conclusion</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Disinformation, social media, and political orientation</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Data<a href="data.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="sources" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Sources<a href="data.html#sources" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data used in this project was originally collected by a team based in California State University San Marcos, and led by <a href="https://scholar.google.com/citations?user=PxQ8_zEAAAAJ&amp;hl=en&amp;oi=ao">Dr. Dustin Calvillo</a>. A visit to his Google Scholar profile indicates that his recent research has focused on employing quantitative methods from cognitive psychology to the study of contemporary communication phenomena, especially mis- and disinformation.
This specific data set – <a href="https://osf.io/fqncj">the fake news and confirmation bias</a> – is part of the <a href="https://osf.io/e6jy4/">Confirmation bias in fact checking political claims research project</a>. There is a similar dataset in the same project, which is apparently a previous version of the one used in this project (suffixes x1 and x2, respectively. Although both datasets share the same variables, a few are present in one and not in the other. For example, “disconfirm_bias” is present in x1, but not in x2; the opposite is true for “ideology” and “condition” (referring to “fact-checking conditions”). More clarification was requested via email to the principal investigator, but we are assuming that x2 is a more refined version of x1, so we opted to use the former for our analysis.
The dataset has 247 observations of 53 variables, all of which are “double.” However, the data dictionary indicates that many of those represent other types of data and have possibly been transformed by the authors before publishing the data set. For example, the variable <code>pol_party</code> originally has values “Democrat” and “Repubican,” which are now represented by 1 and 2, respectively; <code>gender</code> originally accepted values “female,” “male,” “other,” and “decline to state,” and now are coded from 1 to 4, in that order. Others are originally integers, for example, <code>t_concordant</code>, which represents “total number f fact-checks for true politically concordant headlines.” The same is true for the Likert-type scale variable <code>ideology</code>, whose rating ranges from 1 to 7, “from extremely liberal to extremely conservative.” A third class that was present in the original dataset was “time,” the case, for example, of <code>T_dem_rt</code> (“mean reading time for true pro-liberal headlines”). Lastly, there are 2 variables that gorup other variables: <code>CRT```` is the “total number of CRT items answered correctly” (0-6); and</code>AOT```, which is the mean of items in the “active open-minded thinking” (1-5).
One possible challenge that may arise as we start the exploratory data analysis is the transformation of time values form doubles to time and date format. In terms of missing values, although the data set seems to have been pre-processed in order to exclude NAs, there are 4 observations that contain missing values (1 NA each).</p>
<pre><code>## [1] 247  53</code></pre>
<pre><code>## tibble [247 × 53] (S3: tbl_df/tbl/data.frame)
##  $ pol_party          : dbl+lbl [1:247] 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
##    ..@ format.spss: chr &quot;F8.2&quot;
##    ..@ labels     : Named num [1:2] 1 2
##    .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;democrat&quot; &quot;republican&quot;
##  $ condition          : dbl+lbl [1:247] 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
##    ..@ format.spss: chr &quot;F8.2&quot;
##    ..@ labels     : Named num [1:2] 1 2
##    .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;easy&quot; &quot;difficult&quot;
##  $ t_concordant       : num [1:247] 0 3 6 5 3 6 5 6 5 6 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ f_concordant       : num [1:247] 3 4 6 5 1 6 5 5 6 6 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ t_discordant       : num [1:247] 1 2 6 6 1 5 6 3 6 2 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ f_discordant       : num [1:247] 0 3 6 6 5 5 5 2 6 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ age                : num [1:247] 34 66 57 25 26 54 30 41 46 27 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ gender             : dbl+lbl [1:247] 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
##    ..@ format.spss: chr &quot;F8.2&quot;
##    ..@ labels     : Named num [1:4] 1 2 3 4
##    .. ..- attr(*, &quot;names&quot;)= chr [1:4] &quot;female&quot; &quot;male&quot; &quot;other&quot; &quot;decline&quot;
##  $ ideology           : num [1:247] 2 1 3 2 2 2 3 1 3 2 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ CRT                : num [1:247] 4 6 4 2 6 6 6 5 3 2 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ AOT                : num [1:247] 3.64 4.73 4.18 4.18 4.27 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ confirmation_bias  : num [1:247] 2 2 0 -2 -2 2 -1 6 -1 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 19
##  $ T_dem_rt           : num [1:247] 2.03 3.98 2.56 6.09 1.36 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ F_dem_rt           : num [1:247] 4.46 5.12 4.32 5.17 0.9 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ T_rep_rt           : num [1:247] 5.27 5.05 5.7 6.53 1.72 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ F_rep_rt           : num [1:247] 2.69 4.14 1.86 8.39 1.64 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ t_concordant_rt    : num [1:247] 2.03 3.98 2.56 6.09 1.36 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 17
##  $ f_concordant_rt    : num [1:247] 4.46 5.12 4.32 5.17 0.9 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 17
##  $ t_discordant_rt    : num [1:247] 5.27 5.05 5.7 6.53 1.72 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 17
##  $ f_discordant_rt    : num [1:247] 2.69 4.14 1.86 8.39 1.64 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 17
##  $ crt1               : num [1:247] 0 1 0 0 1 1 1 0 0 0 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ crt2               : num [1:247] 1 1 0 0 1 1 1 1 0 0 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ crt3               : num [1:247] 0 1 1 1 1 1 1 1 0 0 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ crt4               : num [1:247] 1 1 1 0 1 1 1 1 1 0 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ crt5               : num [1:247] 1 1 1 1 1 1 1 1 1 1 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ crt6               : num [1:247] 1 1 1 0 1 1 1 1 1 1 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot01              : num [1:247] 4 5 4 5 4 5 4 3 4 3 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot02              : num [1:247] 4 5 5 5 5 5 4 5 4 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot03              : num [1:247] 2 5 5 1 4 5 4 4 4 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot04              : num [1:247] 4 5 5 4 5 5 4 4 3 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot05              : num [1:247] 4 5 5 5 5 5 5 5 5 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot06              : num [1:247] 4 5 5 5 4 4 3 4 4 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot07              : num [1:247] 4 5 4 5 4 5 4 5 5 1 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot08              : num [1:247] 4 5 2 5 4 5 5 5 4 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot09              : num [1:247] 4 3 2 5 4 3 3 2 3 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot10              : num [1:247] 3 5 5 2 4 3 2 4 3 2 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ aot11              : num [1:247] 4 5 5 5 5 4 4 5 5 5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ fc_att1            : num [1:247] 5 6 6 7 6 7 5 6 5 3 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ fc_att2            : num [1:247] 4 6 6 6 6 6 5 6 4 4 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ fc_att3            : num [1:247] NA 6 6 7 6 7 5 6 5 1 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##  $ fact_check_att     : num [1:247] 4.5 6 6 6.67 6 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 16
##  $ total_fact_checks  : num [1:247] 4 12 24 22 10 22 21 16 23 19 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 19
##  $ concordant_rt      : num [1:247] 3.24 4.55 3.44 5.63 1.13 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 15
##  $ discordant_rt      : num [1:247] 3.98 4.59 3.78 7.46 1.68 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 15
##  $ t_rt               : num [1:247] 3.65 4.51 4.13 6.31 1.54 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 10
##  $ f_rt               : num [1:247] 3.57 4.63 3.09 6.78 1.27 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 10
##  $ filter_$           : dbl+lbl [1:247] 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
##    ..@ label        : chr &quot;condition=2 (FILTER)&quot;
##    ..@ format.spss  : chr &quot;F1.0&quot;
##    ..@ display_width: int 10
##    ..@ labels       : Named num [1:2] 0 1
##    .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;Not Selected&quot; &quot;Selected&quot;
##  $ overall_rt         : num [1:247] 3.61 4.57 3.61 6.54 1.41 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 12
##  $ overall_fact_checks: num [1:247] 1 3 6 5.5 2.5 5.5 5.25 4 5.75 4.75 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 21
##  $ m_concordant_fc    : num [1:247] 1.5 3.5 6 5 2 6 5 5.5 5.5 6 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 17
##  $ m_discordant_fc    : num [1:247] 0.5 2.5 6 6 3 5 5.5 2.5 6 3.5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 17
##  $ m_true_fc          : num [1:247] 0.5 2.5 6 5.5 2 5.5 5.5 4.5 5.5 4 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 11
##  $ m_false_fc         : num [1:247] 1.5 3.5 6 5.5 3 5.5 5 3.5 6 5.5 ...
##   ..- attr(*, &quot;format.spss&quot;)= chr &quot;F8.2&quot;
##   ..- attr(*, &quot;display_width&quot;)= int 12</code></pre>
<pre><code>##                                variable  class
## pol_party                     pol_party double
## condition                     condition double
## t_concordant               t_concordant double
## f_concordant               f_concordant double
## t_discordant               t_discordant double
## f_discordant               f_discordant double
## age                                 age double
## gender                           gender double
## ideology                       ideology double
## CRT                                 CRT double
## AOT                                 AOT double
## confirmation_bias     confirmation_bias double
## T_dem_rt                       T_dem_rt double
## F_dem_rt                       F_dem_rt double
## T_rep_rt                       T_rep_rt double
## F_rep_rt                       F_rep_rt double
## t_concordant_rt         t_concordant_rt double
## f_concordant_rt         f_concordant_rt double
## t_discordant_rt         t_discordant_rt double
## f_discordant_rt         f_discordant_rt double
## crt1                               crt1 double
## crt2                               crt2 double
## crt3                               crt3 double
## crt4                               crt4 double
## crt5                               crt5 double
## crt6                               crt6 double
## aot01                             aot01 double
## aot02                             aot02 double
## aot03                             aot03 double
## aot04                             aot04 double
## aot05                             aot05 double
## aot06                             aot06 double
## aot07                             aot07 double
## aot08                             aot08 double
## aot09                             aot09 double
## aot10                             aot10 double
## aot11                             aot11 double
## fc_att1                         fc_att1 double
## fc_att2                         fc_att2 double
## fc_att3                         fc_att3 double
## fact_check_att           fact_check_att double
## total_fact_checks     total_fact_checks double
## concordant_rt             concordant_rt double
## discordant_rt             discordant_rt double
## t_rt                               t_rt double
## f_rt                               f_rt double
## filter_$                       filter_$ double
## overall_rt                   overall_rt double
## overall_fact_checks overall_fact_checks double
## m_concordant_fc         m_concordant_fc double
## m_discordant_fc         m_discordant_fc double
## m_true_fc                     m_true_fc double
## m_false_fc                   m_false_fc double</code></pre>
<pre><code>## 
##                 age                 AOT               aot01               aot02               aot03               aot04               aot05               aot06               aot07               aot08 
##                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1 
##               aot09               aot10               aot11       concordant_rt           condition   confirmation_bias                 CRT                crt1                crt2                crt3 
##                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1 
##                crt4                crt5                crt6       discordant_rt        f_concordant     f_concordant_rt            F_dem_rt        f_discordant     f_discordant_rt            F_rep_rt 
##                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1 
##                f_rt      fact_check_att             fc_att1             fc_att2             fc_att3            filter_$              gender            ideology     m_concordant_fc     m_discordant_fc 
##                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1 
##          m_false_fc           m_true_fc overall_fact_checks          overall_rt           pol_party        t_concordant     t_concordant_rt            T_dem_rt        t_discordant     t_discordant_rt 
##                   1                   1                   1                   1                   1                   1                   1                   1                   1                   1 
##            T_rep_rt                t_rt   total_fact_checks 
##                   1                   1                   1</code></pre>
</div>
<div id="cleaning-transformation" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Cleaning / transformation<a href="data.html#cleaning-transformation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First, the data set is loaded in using the package Haven’s read_sav() function, as the data is stored as a .SAV file. This type of file is outputted by the application SPSS. It is then converted to a data frame for easier use. The authors of this study clearly spent time preparing their data for publishing and little transformation was needed. Upon examination, there are many categorical variables which have already been modified to be numeric, ordinal variables. However, they are still numeric and plotting in ggplot2 often requires ordinal variables to be in factor form. As such, many columns will need to be converted to factors. This is done with a custom function factor_converter() which takes columns and a data set as a inputs and creates factor level variables, including an NA factor. One option to explore is modifying some of these ordinal variables to be binary, as using ordinal scale on data that shouldn’t be ranked can obscure true relationships. Given this data relates to individual participants and their responses in the study, a new variable participant_id has been added to the data set to uniquely identify each participant. This allowed us to track whether any anomalies were related to specific individuals. For now, this allows us to move straight into exploratory data analysis.</p>
</div>
<div id="missing-value-analysis" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Missing value analysis<a href="data.html#missing-value-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The authors mention that missing values have been removed prior to the data being made publicly available. However, there do seem to be a few missing observations present in the data.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>After finding and selecting all columns that have missing values, we show below only the participants and columns that contained missing values to see if any were in common:</p>
<pre><code>##   participant_id aot01 aot04 aot09 fc_att3
## 1              1     4     4     4      NA
## 2            197     3     4    NA       3
## 3            213    NA     4     2       5
## 4            215     4    NA     2       3</code></pre>
<p>Now we look to investigate whether there were any similarities among these four participants:</p>
<pre><code>## # A tibble: 4 × 11
##   participant_id aot01 aot04 aot09 fc_att3 gender     pol_party      ideology condition       age   AOT
##            &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl+lbl&gt;  &lt;dbl+lbl&gt;         &lt;dbl&gt; &lt;dbl+lbl&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1              1     4     4     4      NA 1 [female] 1 [democrat]          2 1 [easy]         34  3.64
## 2            197     3     4    NA       3 1 [female] 2 [republican]        7 2 [difficult]    69  3.6 
## 3            213    NA     4     2       5 2 [male]   2 [republican]        5 2 [difficult]    26  3.4 
## 4            215     4    NA     2       3 1 [female] 2 [republican]        7 2 [difficult]    77  3.3</code></pre>
<p>Variables:</p>
<p>AOT: mean rating for 11 actively open-minding thinking questions (possible range of 1-5)<br />
fact_check_att: mean rating for three attitude toward fact-checkers questions (possible range of 1-7)<br />
fc_att3: response to the third item on the attitudes toward fact-checkers scale<br />
aot01: response to the first item on the actively open-minded thinking scale (1-5)<br />
aot04: response to the fourth item on the actively open-minded thinking scale (1-5)<br />
aot09: response to the nineth item on the actively open-minded thinking scale (1-5)<br />
</p>
<p>There seems to be little in common among the four participants on first glance. However, all four score roughly a 3.5 on the AOT mean rating for 11 actively open minded thinking questions. Considering the scale goes up to only five, this means these participants were on the higher end in terms of their willingness to explore alternate ways of thinking. Considering aot01, aot04, and aot09 are all scores for questions intended to judge a participants open minded thinking, one theory could be that these participants believed the question was neutral, it was outside of their realm of knowledge, or they just couldn’t think of black and white answer so they left it blank. But the fact that all three missing aot particpants are republican, with two having the highest ideology rating of seven meaning they are extremely conservative (participants 197 and 215), gives rise to a few theories of why this occurred. Perhaps a question was asked that disagreed with them morally, such as abortion or the death penalty. This may have led them to give no response to this question. This theory can better be confirmed by the fact that participant 215 was not very open minded in regards to the ninth question, aot09, and only scored a 2 out of 5. Participant 197 chose not to answer this question at all. Both also scored relatively low on questions intended to gauge the participants attitudes towards fact checkers, 2 and 3 out of 7, so maybe they felt uncomfortable sharing their views with the the proctor. Another idea could be that these three participants simply had a hard time answering these questions because the fact checking conditions were difficult (condition = 2). This ma have made them more guarded in terms of their willingness to answer these type of questions. As for participant 1, she is a democrat who is extremely liberal with an ideology score of 2, with one being extremely liberal and seven being extremely conservative. fc_att3 was one of the questions given to participants to gauge their attitudes toward fact checkers. Overall, participant 1 scored relatively high in terms of her attitude toward fact checkers, 4.3/7. So it seems that overall she felt positively about fact checkers, but maybe considering she’s extremely liberal, she didn’t feel that question was appropriate. All four are still valid participants to include in the study considering all other questions were answered, so it makes sense that the authors left them in.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="proposal.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="results.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/katlass/media_disinformation/edit/main/data.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/katlass/media_disinformation/blob/main/data.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
